### ISSUE TITLE
Minimum GPU Memory Requirement for Running the Experiment

### ISSUE THREAD

**Issue by JustCoolPig** [cvl-umass/AdaptCLIPZS#1]
Hello,

I recently came across your research paper and noticed that you have conducted your experiments using an NVIDIA A100 GPU. I am very interested in following your work and replicating the experiments. However, my current GPU has less than 80GB of memory, and I am concerned about the minimum GPU memory requirements for running your experiment.

Could you please provide information on the minimum GPU memory requirement to successfully execute the experiments in your repository? It would be greatly appreciated if you could share any possible workarounds or suggestions for running the experiments on GPUs with lower memory capacities.

Thank you in advance for your time and assistance. I am looking forward to your response.

Best regards

**Comment by oindrilasaha** [comment]
Hey Biao, thank you for your interest in our work! 
We train on A100s primarily to utilize high batch sizes. However, the training can be carried out easily on any GPU if you lower the batch size. The hyperparameters need to be tuned wrt to the new batch size to ensure the highest possible improvement. Usually, the learning rates might need to be lowered, and it may be fine if the weight decays are kept the same. We list our hyperparameters in the paper for 1024 batch size. Hope this helps!

**Comment by JustCoolPig** [comment]
Thank you very much for your swift response.
