### ISSUE TITLE
a small question

### ISSUE THREAD

**Issue by Kirito-Asuna-Yu** [cvl-umass/AdaptCLIPZS#2]
there is something wrong with finetune_clip_nat.py，maybe the all_classes is a dictionary，how should i do to solve this problem？
![error](https://github.com/cvl-umass/AdaptCLIPZS/assets/67791902/cf3c3431-8222-4bfe-b39d-e1937f8a8d05)

**Comment by oindrilasaha** [comment]
Sorry for the delayed response! Can you tell me the command you ran?

**Comment by Kirito-Asuna-Yu** [comment]
sorry for the late, and I saw you have solved above problems, but there is a new problem
![QQ截图20240710122812](https://github.com/cvl-umass/AdaptCLIPZS/assets/67791902/4ae13f3b-afaf-4271-a7ae-e403e86c69ff)
the command I ran is that：python finetune_clip_nat.py --dataset Flowers102 --im_dir ./dataset/oxford_flowers/jpg --fewshot --arch ViT-B/16 --save_dir ./checkpoints/ft_clip_flowers102 --text_dir_viz ./gpt_descriptions/gpt4_0613_api_Flowers102 --text_dir_loc ./gpt_descriptions/gpt4_0613_api_Flowers102_location
the ./dataset/oxford_flowers/jpg contains a lot of jpg files, but train_dataloader is null

**Comment by oindrilasaha** [comment]
Thanks for pointing this out. The Flower data needs to be downloaded from https://www.kaggle.com/datasets/nunenuh/pytorch-challange-flower-dataset 
The path specified in the command should be the enclosing folder of the whole dataset in all cases.

**Comment by Kirito-Asuna-Yu** [comment]
thank you for your answer, that's great!
